# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/hana
    REF boost-${VERSION}
    SHA512 addcbeb1427b1e85aed9fbb8084c0de9e0acab3d1fb721d4f7b6c20b00d875c4b5aa97b7493c06ebbe5eb6ffea3d66f2845283ede5eb46acc9576ca7a4615685
    HEAD_REF master
    )

set( headers_only OFF )
if (NOT EXISTS "${SOURCE_PATH}/src") # regex|system|math are header only and only install libs due to compat
    set( headers_only ON )
    set( VCPKG_BUILD_TYPE release )
endif ()

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
    )

vcpkg_cmake_install()

vcpkg_cmake_config_fixup( PACKAGE_NAME Hana CONFIG_PATH lib/cmake/hana )

if (headers_only)
    file( REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib" "${CURRENT_PACKAGES_DIR}/debug/lib" )
endif ()

file( REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share"
    "${CURRENT_PACKAGES_DIR}/debug/include"
    )

vcpkg_fixup_pkgconfig()

vcpkg_install_copyright( FILE_LIST "${SOURCE_PATH}/LICENSE.md" )

